### ISSUE TITLE
Title change!

### ISSUE THREAD

**Issue by FoxyboiTia** [ijre/EVE-Online_Discord-RPC#1]
Hi there! is there a way to change the title to "Eve online" instead of "Eve online Rich presense" on discord? the name doesnt fit on all resolutions

**Comment by ijre** [comment]
Hi! There IS technically a way to change it yourself, but this made me realize that it should already be "Eve Online", as in, it would just be a better idea for me to rename it to that myself as it's just a straight up improvement since adding Rich Presence to the name is redundant, which I will do after I send this reply.

BUT! If you're still interesting in knowing how to do this yourself anyways, for whatever reason:

Step 1: Clone the repo
Step 2: Go to [here](https://discordapp.com/developers/applications/) and create an application
The only thing that matters here is the name specifically, nothing else

Step 3: At [this line in the code](https://github.com/ijre/EVE-Online-Discord-Rich-Presence/blob/master/Form1.cs#L20), change the long stream of numbers to your new client ID number, located in the General Information tab in the page of the application you created
Step 4 & 5: Build the project in Release and run

Sadly as you could probably tell, Discord's Rich Presence API doesn't support changing the title of the game or program, this is pretty much the only real way of doing it

(you could *theoretically* program something that used POST requests which changed the title for you, using your username, password, and auth code, (if you had one) but im extremely inexperienced with such things, so i wouldnt even know where to begin)
